services:
  db:
    image: mysql:8.0.44
    container_name: smartfix-db
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: smartfix-backend
    restart: always
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASSWORD};
    volumes:
      # Монтируем общую папку для аватарок (путь зависит от WORKDIR в Dockerfile бэкенда, обычно это /app)
      - ./data/uploads:/app/wwwroot/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Refactor/Front
      dockerfile: Dockerfile
      args:
      - VITE_API_URL=http://backend:80
    container_name: smartfix-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:80
    volumes:
      - ./Backend/wwwroot/avatars:/usr/share/nginx/html/avatars:ro
      - ./Backend/wwwroot/services:/usr/share/nginx/html/services:ro
      - ./data/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - backend

volumes:
  mysql_data:
  static_files:  # Объявляем новый именованный volume для статических файлов
