services:
  smartfix-db:
    image: mysql:8.0.44
    container_name: smartfix-db
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5

  smartfix-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartfix-backend
    restart: always
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
    environment:
      ConnectionStrings__DefaultConnection: "Server=smartfix-db;Port=3306;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./data/uploads:/app/wwwroot/uploads
      - ./backend/wwwroot/avatars:/app/wwwroot/avatars
    networks:
      - app-network
    depends_on:
      smartfix-db:
        condition: service_healthy

  smartfix-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://smartfix.amadesu.space/api
    container_name: smartfix-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://smartfix.amadesu.space/api
    volumes:
      - ./backend/wwwroot/avatars:/usr/share/nginx/html/avatars:ro
      - ./backend/wwwroot/services:/usr/share/nginx/html/services:ro
      - ./data/uploads:/usr/share/nginx/html/uploads:ro
    networks:
      - app-network
    depends_on:
      - smartfix-backend
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  static_files: